language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo apt-get install libstdc++-4.8-dev
  - sudo apt-get remove cmake
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=program-options,filesystem,regex)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install)
  # install cmake
  - CMAKE_VERSION="3.0.0"
  - wget "http://www.cmake.org/files/v3.0/cmake-${CMAKE_VERSION}.tar.gz"
  - openssl sha1 "cmake-${CMAKE_VERSION}.tar.gz"
  - tar xf "cmake-${CMAKE_VERSION}.tar.gz"
  - cd "cmake-${CMAKE_VERSION}"
  - ./bootstrap --prefix=~
  - make
  - make install
  - export PATH="~/bin:${PATH}"
  - cd ..
compiler:
  - gcc
script: cmake CMakeLists.txt && make && ctest --timeout 30
notifications:
  email:
    recipients:
      - nes77@cornell.edu
    on_success: change
    on_failure: always
